#!/bin/sh
loc=`realpath "$0"`
d=`dirname "$loc"`
executable=$d/roll.amd64-darwin
rlwrap=`which rlwrap`
if [[ -z "$rlwrap" ]]
then
    echo "Please install rlwrap"
    rlwrap=""
fi
$rlwrap /usr/local/smlnj/bin/sml @SMLload="$executable" $@
